apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: kong-apigw-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/kong-apigw
