apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-cassandra-0
  namespace: devops
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 1Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
