apiVersion: v1
kind: Service
metadata:
  name: konga-pgsql
spec:
  ports:
  - name: pgsql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: konga-pgsql

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: konga-pgsql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: konga-pgsql
    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          env:
            - name: POSTGRES_USER
              value: konga
            - name: POSTGRES_PASSWORD
              value: konga
            - name: POSTGRES_DB
              value: konga
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          emptyDir: {}

