apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: konga
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga
        env:
          - name: DB_ADAPTER
            value: postgres
          - name: DB_HOST
            value: konga-pgsql
          - name: DB_PORT
            value: 5432
          - name: DB_USER
            value: konga
          - name: DB_PASSWORD
            value: konga
          - name: DB_DATABASE
            value: konga
          - name: DB_PG_SCHEMA
            value: konga
          - name: KONGA_LOG_LEVEL
            value: error
          - name: NODE_ENV
            value: production
        ports:
        - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: konga-svc
spec:
  type: LoadBalancer
  ports:
  - name: kong-proxy
    port: 1337
    targetPort: 1337
    protocol: TCP
  selector:
    app: konga
